Band.create(name: "Kanye West")
Band.create(name: "Jai Paul")
Band.create(name: "Elvis")
Band.create(name: "Whatever Else")

Album.create(title: "Graduation", band_id: 1, recording_type: "Studio")
Album.create(title: "Late Registration", band_id: 1, recording_type: "Studio")
Album.create(title: "Something", band_id: 2, recording_type: "Live")
Album.create(title: "Elvis", band_id: 3, recording_type: "Studio")
Album.create(title: "Houndog", band_id: 3, recording_type: "Live")
